//
//  Book.swift
//  
//
//  Created by Matt Kobs on 1/10/20.
//

import Foundation

enum Book: Int {
    case genesis = 1,
        exodus,
        leviticus,
        numbers,
        deuteronomy,
        joshua,
        judges,
        ruth,
        firstSamuel,
        secondSamuel,
        firstKings,
        secondKings,
        firstChronicles,
        secondChronicles,
        ezra,
        nehemiah,
        esther,
        job,
        psalms,
        proverbs,
        ecclesiastes,
        songOfSolomon,
        isaiah,
        jeremiah,
        lamentations,
        ezekiel,
        daniel,
        hosea,
        joel,
        amos,
        obadiah,
        jonah,
        micah,
        nahum,
        habakkuk,
        zephaniah,
        haggai,
        zechariah,
        malachi,
        matthew,
        mark,
        luke,
        john,
        acts,
        romans,
        firstCorinthians,
        secondCorinthians,
        galatians,
        ephesians,
        philippians,
        colossians,
        firstThessalonians,
        secondThessalonians,
        firstTimothy,
        secondTimothy,
        titus,
        philemon,
        hebrews,
        james,
        firstPeter,
        secondPeter,
        firstJohn,
        secondJohn,
        thirdJohn,
        jude,
        revelation
}
